---
# Installed using ansible-galaxy collection -r requirements.txt
collections:
  - name: ansible.utils
  - name: community.general
  - name: ansible.posix
roles:
  - name: google_drive_mount
    src: https://github.com/genirohtea/google-drive-mount
    version: main
