---
extends: default

rules:
  truthy:
    allowed-values: ["true", "false"]
  line-length:
    max: 120
    level: warning
  braces: # Linter is broken on for brace spacing
    min-spaces-inside: -1
    max-spaces-inside: -1
  comments:
    min-spaces-from-content: 1 # Used to follow prettier standard: https://github.com/prettier/prettier/pull/10926
ignore:
  - galaxy.yml
  - .github/
