---
- name: "Install the various proxmox roles"
  hosts: all
  pre_tasks:
    - name: Verify Ansible is version 2.15 or above. (If this fails you may need to update Ansible)
      assert:
        that: "ansible_version.full is version_compare('2.15', '>=')"
        msg: >
          "Ansible is out of date."
  roles:
    - role: disable_subscription_nag
      tags: disable_subscription_nag
    - role: fix_package_repos
      tags: fix_package_repos
    - role: remove_kernels
      tags: remove_kernels
      when: "'pve' in hostvars[inventory_hostname].ansible_kernel"
    - role: cpu_microcode
      tags: cpu_microcode
    - role: intel_graphics
      tags: intel_graphics
    - role: ipmi_fan_control
      tags: ipmi_fan_control
    - role: gpu_passthrough
      tags: gpu_passthrough
    - role: nvidia_vgpu
      tags: nvidia_vgpu
    - role: coral
      tags: coral
    # - role: terraform_user
    #   tags: terraform_user
    - role: admin_user
      tags: admin_user
    - role: download_isos
      tags: download_isos
