---
# handlers file for cpu_microcode

- name: "Restart to install microcode"
  reboot:
    msg: "Force a reboot to allow microcode to be updated"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 5
    post_reboot_delay: 30
    test_command: uptime
  when: hostvars[inventory_hostname].allow_reboot
  become: true
