---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Check distro
      debug:
        msg: "{{ ansible_facts['distribution_release'] }}"

    - name: Update apt cache on Debian Linux.
      ansible.builtin.apt:
        update_cache: True
        cache_valid_time: 600
      when: ansible_facts.os_family == 'Debian'

    - name: Install bws sdk
      ansible.builtin.pip:
        # 0.1.1 has error: 'BitwardenClient' object has no attribute 'access_token_login'
        name: bitwarden-sdk==0.1.0
        state: present
      delegate_to: localhost

    - name: Show ansible version
      ansible.builtin.debug:
        msg: "Ansible Version: {{ ansible_version.full }}"

- name: Run playbook
  ansible.builtin.import_playbook: ../../main.yml
  vars:
    allow_reboot: true
    pinned_kernel_version: "6.5.13-3-pve"
