---
# yamllint disable-rule rule:line-length
- name: "NVIDIA GPU Configuration Block"
  become: true
  when: allow_reboot
  block:
    - name: "Set KVM options for NVIDIA cards"
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/kvm.conf
        line: options kvm ignore_msrs=1 report_ignored_msrs=0
        create: true
        owner: root
        group: root
        mode: 0600

    - name: "Get PCI IDs for NVIDIA GPU"
      ansible.builtin.shell: >-
        set -o pipefail;
        lspci -nn | grep 'NVIDIA'
      register: nvidia_pci_info
      changed_when: false
      args:
        executable: /bin/bash

    - name: "Extract PCI IDs for NVIDIA GPU"
      ansible.builtin.set_fact:
        nvidia_pci_ids: "{{ nvidia_pci_info.stdout_lines | map('regex_findall', '\\[([0-9a-fA-F]{4}:[0-9a-fA-F]{4})\\]') | map('first') | list }}"

    - name: "Ensure vfio-pci module is loaded before other drivers for NVIDIA"
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/vfio.conf
        line: "{{ item }}"
        create: true
        owner: root
        group: root
        mode: 0600
      loop:
        - "options vfio-pci ids={{ nvidia_pci_ids | join(',') }}"
        - "softdep nouveau pre: vfio-pci"
        - "softdep nvidia pre: vfio-pci"
        - "softdep nvidiafb pre: vfio-pci"
        - "softdep nvidia_drm pre: vfio-pci"
        - "softdep drm pre: vfio-pci"
  rescue:
    - name: "NVIDIA GPU Passthrough failed"
      ansible.builtin.set_fact:
        task_failed: true
