---
name: Create Release
on:
  push:
    branches:
      - main

jobs:
  release-create:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Generate release, changelog.
        uses: googleapis/release-please-action@v4.1.3
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `RELEASE_PLEASE_TOKEN` (this secret name is not important).
          # PAT created with `Pull Requests` & `Contents` RW
          # Token then added to github actions repo secrets for this repo
          # Also: `Allow GitHub Actions to create and approve pull requests`
          token: ${{ secrets.GITHUB_TOKEN }}
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          release-type: simple

  release-issues:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
      issues: write
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v4.13.3"
        with:
          PROJECTS_SECRET: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          # Add ignore regex here
          # IGNORE: "plugins.*"
