---
name: Molecule Test Suite
on:
  push:

  pull_request:
    branches:
      - main
      - master
jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - uses: gofrolist/molecule-action@v2
