---
# This workflow requires a GALAXY_API_KEY secret present in the GitHub
# repository or organization.
#
# See: https://github.com/marketplace/actions/publish-ansible-role-to-galaxy
# See: https://github.com/ansible/galaxy/issues/46

name: Publish Release
on:
  push:
    tags:
      - '*'

jobs:
  check-secret:
    runs-on: ubuntu-latest
    outputs:
      ansible-galaxy-key-exists: ${{ steps.ansible-galaxy-key-check.outputs.defined }}
    steps:
      - name: Check for Secret availability
        id: ansible-galaxy-key-check
        # perform secret check & put boolean result as an output
        shell: bash
        run: |
          if [ "${{ secrets.GALAXY_API_KEY }}" != '' ]; then
            echo "defined=true" >> "${GITHUB_OUTPUT}";
          else
            echo "defined=false" >> "${GITHUB_OUTPUT}";
          fi

  publish-ansiblegalaxy:
    if: needs.check-secret.outputs.ansible-galaxy-key-exists == 'true'
    needs: [check-secret]
    defaults:
      run:
        # Working directory is a relative path from github.workspace
        # Workpace: /home/runner/work/<repo>/<repo>
        # Workng Drectory: /home/runner/work/<repo>/<repo>/<user>/<repo>
        working-directory: "${{ github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"

      # Add steps to release project here
      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible.
        run: pip3 install ansible-core

      - name: Trigger a new import on Galaxy.
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }}
          "$(echo ${{ github.repository }} | cut -d/ -f1)" "$(echo ${{ github.repository }} | cut -d/ -f2)"
